In [1]:
import math
import pandas as pd

pd.set_option('display.max_columns', None)

### Landing errors
The following file contains the position of the landing platform and the position of the drone when landed in the simulated environment (centroid coordinates (x,y) and angle in radians). The data provided correspond to the tests of the three controllers (P, PI and PID). There are six columns per controller, three of them for the plaftorm's position an the other three for the drone's position.

In [2]:
file = "./data/landing_2.csv"
data = pd.read_csv(file)

In [3]:
data

,P_platform_x,P_platform_y,P_platform_yaw,P_pos_x,P_pos_y,P_pos_yaw,PI_platform_x,PI_platform_y,PI_platform_yaw,PI_pos_x,PI_pos_y,PI_pos_yaw,PID_platform_x,PID_platform_y,PID_platform_yaw,PID_pos_x,PID_pos_y,PID_pos_yaw
0,3.685,4.692,0.7,3.698,4.664,0.714,3.685,4.692,0.7,3.721,4.695,0.726,3.685,4.692,0.7,3.734,4.696,0.708
1,3.685,4.692,0.7,3.659,4.693,0.705,3.685,4.692,0.7,3.730,4.656,0.720,3.685,4.692,0.7,3.682,4.627,0.723
2,3.685,4.692,0.7,3.707,4.726,0.719,3.685,4.692,0.7,3.701,4.691,0.694,3.685,4.692,0.7,3.706,4.668,0.717
3,3.685,4.692,0.7,3.650,4.742,0.704,3.685,4.692,0.7,3.755,4.664,0.715,3.685,4.692,0.7,3.693,4.694,0.716
4,3.685,4.692,0.7,3.711,4.658,0.715,3.685,4.692,0.7,3.690,4.693,0.699,3.685,4.692,0.7,3.748,4.713,0.733

Converting the angle from radians to degrees.

In [4]:
angle_columns = [i for i in data.columns if 'yaw' in i]
for column in angle_columns:
    data[column] = data[column] * 180 / math.pi

In [5]:
data

,P_platform_x,P_platform_y,P_platform_yaw,P_pos_x,P_pos_y,P_pos_yaw,PI_platform_x,PI_platform_y,PI_platform_yaw,PI_pos_x,PI_pos_y,PI_pos_yaw,PID_platform_x,PID_platform_y,PID_platform_yaw,PID_pos_x,PID_pos_y,PID_pos_yaw
0,3.685,4.692,40.107046,3.698,4.664,40.909187,3.685,4.692,40.107046,3.721,4.695,41.596736,3.685,4.692,40.107046,3.734,4.696,40.565412
1,3.685,4.692,40.107046,3.659,4.693,40.393525,3.685,4.692,40.107046,3.730,4.656,41.252961,3.685,4.692,40.107046,3.682,4.627,41.424849
2,3.685,4.692,40.107046,3.707,4.726,41.195665,3.685,4.692,40.107046,3.701,4.691,39.763271,3.685,4.692,40.107046,3.706,4.668,41.081074
3,3.685,4.692,40.107046,3.650,4.742,40.336229,3.685,4.692,40.107046,3.755,4.664,40.966482,3.685,4.692,40.107046,3.693,4.694,41.023778
4,3.685,4.692,40.107046,3.711,4.658,40.966482,3.685,4.692,40.107046,3.690,4.693,40.049750,3.685,4.692,40.107046,3.748,4.713,41.997806

A table with the absulote error and the standard deviation will be made using the position of the platform and the position of the drone for each controller. Remember that the angle was converted from radians to degrees in the cells above.

In [6]:
land_df = pd.DataFrame(columns=["X_error_avg", "X_error_std",
                                "Y_error_avg", "Y_error_std",
                                "Angle_error_avg", "Angle_error_std"],
                       index=["P", "PI", "PID"])

land_df["X_error_avg"]["P"] = abs(data["P_platform_x"]-data["P_pos_x"]).mean()
land_df["X_error_avg"]["PI"] = abs(data["PI_platform_x"]-data["PI_pos_x"]).mean()
land_df["X_error_avg"]["PID"] = abs(data["PID_platform_x"]-data["PID_pos_x"]).mean()

land_df["Y_error_avg"]["P"] = abs(data["P_platform_y"]-data["P_pos_y"]).mean()
land_df["Y_error_avg"]["PI"] = abs(data["PI_platform_y"]-data["PI_pos_y"]).mean()
land_df["Y_error_avg"]["PID"] = abs(data["PID_platform_y"]-data["PID_pos_y"]).mean()

land_df["Angle_error_avg"]["P"] = abs(data["P_platform_yaw"]-data["P_pos_yaw"]).mean()
land_df["Angle_error_avg"]["PI"] = abs(data["PI_platform_yaw"]-data["PI_pos_yaw"]).mean()
land_df["Angle_error_avg"]["PID"] = abs(data["PID_platform_yaw"]-data["PID_pos_yaw"]).mean()

land_df["X_error_std"]["P"] = abs(data["P_platform_x"]-data["P_pos_x"]).std()
land_df["X_error_std"]["PI"] = abs(data["PI_platform_x"]-data["PI_pos_x"]).std()
land_df["X_error_std"]["PID"] = abs(data["PID_platform_x"]-data["PID_pos_x"]).std()

land_df["Y_error_std"]["P"] = abs(data["P_platform_y"]-data["P_pos_y"]).std()
land_df["Y_error_std"]["PI"] = abs(data["PI_platform_y"]-data["PI_pos_y"]).std()
land_df["Y_error_std"]["PID"] = abs(data["PID_platform_y"]-data["PID_pos_y"]).std()

land_df["Angle_error_std"]["P"] = abs(data["P_platform_yaw"]-data["P_pos_yaw"]).std()
land_df["Angle_error_std"]["PI"] = abs(data["PI_platform_yaw"]-data["PI_pos_yaw"]).std()
land_df["Angle_error_std"]["PID"] = abs(data["PID_platform_yaw"]-data["PID_pos_yaw"]).std()

land_df

,X_error_avg,X_error_std,Y_error_avg,Y_error_std,Angle_error_avg,Angle_error_std
P,0.0244,0.00795613,0.0294,0.017855,0.653172,0.377022
PI,0.0344,0.0254224,0.0138,0.0168731,0.779223,0.582335
PID,0.0288,0.0261572,0.0232,0.0253515,1.11154,0.532265